/** @type {import("tailwindcss").Config} */
export default {
    content: ["./index.html", "./shader/index.html", "./src/**/*.js"],
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
          "tertiary": "#d8ffe7",
          "on-tertiary-container": "#006d4a",
          "outline-variant": "#3b494b",
          "on-primary-container": "#006970",
          "on-secondary-fixed": "#07006c",
          "surface-tint": "#00dbe9",
          "tertiary-container": "#65f2b5",
          "on-primary-fixed-variant": "#004f54",
          "on-background": "#dfe2f2",
          "on-secondary": "#1000a9",
          "tertiary-fixed": "#6ffbbe",
          "on-tertiary-fixed": "#002113",
          "inverse-on-surface": "#2c303c",
          "outline": "#849495",
          "secondary": "#c0c1ff",
          "secondary-fixed-dim": "#c0c1ff",
          "on-error-container": "#ffdad6",
          "primary-fixed-dim": "#00dbe9",
          "error": "#ffb4ab",
          "on-secondary-fixed-variant": "#2f2ebe",
          "primary-container": "#00f0ff",
          "surface-container-low": "#171b27",
          "primary-fixed": "#7df4ff",
          "surface-dim": "#0f131e",
          "on-secondary-container": "#b0b2ff",
          "on-error": "#690005",
          "on-tertiary-fixed-variant": "#005236",
          "secondary-fixed": "#e1e0ff",
          "surface-variant": "#313441",
          "primary": "#dbfcff",
          "on-primary": "#00363a",
          "on-surface-variant": "#b9cacb",
          "tertiary-fixed-dim": "#4edea3",
          "inverse-surface": "#dfe2f2",
          "surface-container-high": "#262a36",
          "on-tertiary": "#003824",
          "background": "#0f131e",
          "surface-container-lowest": "#0a0e19",
          "surface-container-highest": "#313441",
          "on-primary-fixed": "#002022",
          "error-container": "#93000a",
          "on-surface": "#dfe2f2",
          "secondary-container": "#3131c0",
          "surface-container": "#1b1f2b",
          "surface-bright": "#353945",
          "inverse-primary": "#006970",
          "surface": "#0f131e"
        },
        "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
        },
        "spacing": {
          "margin": "2rem",
          "space-xl": "2.5rem",
          "gutter-mobile": "1rem",
          "gutter": "1.5rem",
          "space-xs": "0.25rem",
          "space-sm": "0.5rem",
          "space-md": "1rem",
          "margin-mobile": "1rem",
          "space-lg": "1.5rem"
        },
        "fontFamily": {
          "body-md": ["Inter"],
          "title-md": ["Inter"],
          "headline-lg": ["Plus Jakarta Sans"],
          "headline-sm": ["Plus Jakarta Sans"],
          "label-telemetry": ["JetBrains Mono"],
          "title-lg": ["Inter"],
          "headline-md": ["Plus Jakarta Sans"],
          "display-hero": ["Plus Jakarta Sans"],
          "headline-lg-mobile": ["Plus Jakarta Sans"],
          "label-code": ["JetBrains Mono"],
          "body-lg": ["Inter"],
          "display-hero-mobile": ["Plus Jakarta Sans"],
          "body-sm": ["Inter"]
        },
        "fontSize": {
          "body-md": ["14px", {"lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400"}],
          "title-md": ["16px", {"lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "500"}],
          "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "700"}],
          "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "label-telemetry": ["11px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600"}],
          "title-lg": ["18px", {"lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "headline-md": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "display-hero": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700"}],
          "headline-lg-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "label-code": ["13px", {"lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
          "body-lg": ["16px", {"lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400"}],
          "display-hero-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-sm": ["12px", {"lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400"}]
        }
      }
    }
  }
